apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: nginx
   labels:
      app: nginx
      tire: frontend
spec:
   template: 
     metadata: 
       name: nginx
       labels:
          app: nginx
          tire: frontend
     spec:
       containers: 
       -  name: nginx
          image: nginx
   selector:
      matchLabels:
        app: nginx
   replicas: 3
   